### ISSUE TITLE
Is C3DV 2024 challenge ongoing?

### ISSUE THREAD

**Issue by jk4011** [Vision-CAIR/3DCoMPaT-v2#7]
Hello and thanks for creating fantastic datasets! 
I'm curious if the C3DV 2024 challenge is currently happening. 

According to [the workshop website](https://3dcompat-dataset.org/workshop/C3DV24/#dates-section), the validation and test server should have been online in February, but it appears they are not. Can you please let me know when the challenge is scheduled to take place?

**Comment by HabibSlim** [comment]
Thanks for the enthusiasm!

The challenge is now **online**.
The workshop website has been updated with the challenge.
Looking forward to your submissions!
